name             'sitecore_ext'
maintainer       '@Vapok'
maintainer_email 'vapokrocks@gmail.com'
license          'All rights reserved'
description      'Installs/Configures sitecore_ext'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'sitecore'
depends			 'windows'
depends			 'mongodb3'
depends			 'msazure_expanded'